name: test Go using asdf

on:
  push:
  pull_request:

jobs:
  test-asdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Install ginkgo
        run: GOBIN=$PWD/bin go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Tests
        run: $PWD/bin/ginkgo -r -race --cover --coverprofile=.coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage.out
