name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ["1.19.x", "1.20.x"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        check-latest: true

    - name: Test
      run: go test -v -race ./...
